#!/usr/bin/env bash
# A Bash script to transfer file from a client to a server.
# Display: PATH_TO_FILE to be copied to server, USERNAME path of IP to server
# scp to transfer file to the user directory

if [ $# -lt 4 ]
	then
		echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'

	else
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
