#!/usr/bin/env bash
#s script installs nginx on web 01
#The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'nginx HTTP'

echo 'Hello World'!| sudo tee /var/www/html/index.html

#testing nginx config
sudo nginx -t

# script that configures a new Ubuntu machine to respect above requirements
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/welcome.com

sudo service nginx restart
