#!/usr/bin/env bash
#s script installs nginx on web 01
#The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html
#config a new ubuntu machine
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.no
two

#testing nginx config
sudo nginx -t

sudo service nginx restart
