#!/usr/bin/env bash

#script that configures you nginx server so that /redirect_me redirects to another page
#using sed replace a line with multiple lines
#the redirection is configured as "301 moved permanently"

apt-get update

apt-get install -y nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/brivan1 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled

sudo service nginx restart
