#!usr/bin/env bash

#script tha configures you nginx server so that /redirect_me redirects to another page
# the redirection is configured as "301 moved permanently"

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

#testing nginx config
sudo nginx -t

#redirection config
NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://github.com/brivan1\n\t}\n"

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

# script that configures a new Ubuntu machine to respect above requirements
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default2

sudo service nginx restart
