#!/usr/bin/env bash
# creating a 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/brivan1 permanent;"

sudo sed -i "s/server_name _;/$string_replacement/" /etc/nginx/sites-enabled
#creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tdefault;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
