#!/usr/bin/env bash
#configure Nginx so that its HTTP response contains a custom header(on web-01 and web-02)
#name of the custom HTTP must be X-Served-By
#value of custom HTTP header must be the hostname of the server nginx is running on
#
#nginx indtallation

sudo apt-get update
sudo apt-get install -y nginx

# configure firewall to allow request through port 80

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/

#change permission to allow creation of files in the directory

sudo chmod -R 755 /var/www

#create an index page

echo 'Hello World!' | sudo tee /var/www/html/index.html

#create a redirection 

location="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.co\/brivan1 permanent;"

sudo sed -i "s/server_name _;/$location/" /etc/nginx/sites-enabled/default

#create a custom 404 error webpage

echo "ceci n'est pas une page" | sudo tee /var/www/html/404.html
#configuring redirect for 404 error webpage

location="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;$location/" /etc/nginx/sites-enabled/default

# creating a custom HTTP response header

sudo sed -i "server_name_ ;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#test for config errors
sudo nginx -t

#restart nginx

sudo service nginx restart
