#!/usr/bin/env bash
#a script to install and configure haproxy as a loadbalancer on  lb-01 server


sudo apt-get -y update

sudo apt-get -y install haproxy


server_config=\
"
defaults
   mode http
   timeout client 10000ms
   timeout connect 3000ms
   timeout server 10000ms

frontend brivan.front
        bind *:80
        default_backend brivan.backbencher

backend brivan.backbencher
       balance roundrobin
       server 130215-web-01 100.24.253.196 
       server 130215-web-02 54.234.69.207
"

echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

#test haproxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

#enable HAProxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
