#!/usr/bin/env bash
#script that resolves nginx to listen to default server port 80
echo "
      server{
      listen 80;
      listen [::]:80;

      root /var/www/html
}
" > /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
