#!/usr/bin/env bash
#script that resolves nginx to listen to default server port 80

sudo rm /etc/nginx/sites-enabled/default 
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
