#!/usr/bin/env bash
#A bash script that accepts one argument
# the script runs the 'whoami' command under the user passed as an argument

if id -u "$1" > /dev/null 2>&1;
then
	sudo -u "$1" whoami
else
	echo "$1"
fi
